### ISSUE TITLE
Can't find configurations in the solution by patterns: Installer

### ISSUE THREAD

**Issue by chuongmep** [Nice3point/RevitTemplates#21]
Dear @Nice3point
Currently i am getting this error with config, can you give me some hint info for this, even though i have already added config.
Thanks you.
 ```
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <Optimize>true</Optimize>
        <DebugType>none</DebugType>
    </PropertyGroup>
```
![image](https://user-images.githubusercontent.com/31106432/150491787-42e5572d-d710-473e-938b-140d012e3eb3.png)

**Comment by Nice3point** [comment]
@chuongmep did you create a project based on a template?

**Comment by Nice3point** [comment]
by default, the **Installer** solution configuration is created, you apparently do not have it
![изображение](https://user-images.githubusercontent.com/20504884/150494784-1c256f28-4ad0-4095-bcb9-33360227c3e6.png)

**Comment by chuongmep** [comment]
@Nice3point yes i have, let see https://github.com/chuongmep/RevitAddInManager/tree/dev_NET6
i am making msi installer for addinmanager tool, can you take a look at it ?

**Comment by chuongmep** [comment]
> by default, the **Installer** solution configuration is created, you apparently do not have it ![изображение](https://user-images.githubusercontent.com/20504884/150494784-1c256f28-4ad0-4095-bcb9-33360227c3e6.png)

oh, i miss that, thanks so much

**Comment by Nice3point** [comment]
@chuongmep  there are no configured configurations in the project at all
![изображение](https://user-images.githubusercontent.com/20504884/150495260-aaebd57f-2655-4adf-ab46-b2434ec5e24b.png)

and there is no need to manually copy the code from the RevitLookup project
create a new project with Visual Studio 2022 or use the command line
`dotnet new revit-sln -n RevitAddInManager`
`dotnet new revit-addin -n RevitAddInManager`

**Comment by chuongmep** [comment]
i messed up with release config and project name, thanks a lot, problem resolved.
