### ISSUE TITLE
configuration bug

### ISSUE THREAD

**Issue by gaborschnierer** [Nice3point/RevitTemplates#31]
Hi Roman! I just updated the templates, and to created a new solution. The generated configurations seem like they are messed up. Is it just me?

https://i.imgur.com/GRmceDb.png
https://i.imgur.com/jJpXM1g.png

**Comment by Nice3point** [comment]
Sorry for the issue, a fix has been released in version 3.0.1
`dotnet new install Nice3point.Revit.Templates::3.0.1`

![изображение](https://user-images.githubusercontent.com/20504884/230784729-8989a606-a541-465e-a0d0-59dd5767b2d7.png)
![изображение](https://user-images.githubusercontent.com/20504884/230784737-8b6161fb-bc39-43b5-8660-4ea05a0dcbe5.png)
