### ISSUE TITLE
An item with the same key has already been added. Key: OnlyWhen

### ISSUE THREAD

**Issue by gaborschnierer** [Nice3point/RevitTemplates#32]
Hi Roman!
I ran into an error message when trying to nuke from a git branch other than main/master. 
"An item with the same key has already been added. Key: OnlyWhen"
I got it fixed by removing one of the duplicate OnlyWhenStatic rows in Build.GitHubRelease.cs. Here is a link:
https://github.com/Nice3point/RevitTemplates/blob/c5ce69e961f6bc6f404769b2264c7cdddbc5ab9d/Templates/Nice3point.Revit.Solution/Build/Build.GitHubRelease.cs#L30

**Comment by Nice3point** [comment]
Hi, you probably upgraded Nuke to version 6.3. This check was added in this version. I will update templates soon using source generators, Build project will become a bit easier 😉

**Comment by gaborschnierer** [comment]
Correct, my Nuke nuget package is on 6.3.0. version.
Looking forward to the update, and thanks for all your hard work in this
project!

**Comment by Nice3point** [comment]
> Correct, my Nuke nuget package is on 6.3.0. version.

The templates have so far been released on Nuke version 6.2. So this will all be fixed in an upcoming update, I'm already testing the changes and thinking about how best to add installer variability

**Comment by Nice3point** [comment]
@gaborschnierer hi, beta template version using build source generators and a new Nuke version.

Build.Configuration.cs file is now used to configure the build
Here you must specify the configurations to be compiled. Projects to be built in Bundle, installer

The release is planned for next week after the release of Rider 2023.2 EAP and the WIKI rewrite.

If you have any suggestions to improve the templates, please feel free to write about them

Download beta:
[Nice3point.Revit.Templates.3.1.0.zip](https://github.com/Nice3point/RevitTemplates/files/11405566/Nice3point.Revit.Templates.3.1.0.zip)

Install:
```dotnet new install C:\Downloads\Nice3point.Revit.Templates.3.1.0.nupkg```

Uninstall:
```dotnet new uninstall Nice3point.Revit.Templates```

**Comment by Nice3point** [comment]
[RevitLookup](https://github.com/jeremytammik/RevitLookup) is already using a new version with some changes due to project specifics

**Comment by Nice3point** [comment]
Open voting:
https://github.com/Nice3point/RevitTemplates/discussions/35
https://github.com/Nice3point/RevitTemplates/discussions/33
https://github.com/Nice3point/RevitTemplates/discussions/34

**Comment by Nice3point** [comment]
Fixed in release 3.1.1
