### ISSUE TITLE
ForbiddenException: Resource not accessible by integration when running Nuke

### ISSUE THREAD

**Issue by Yuvdal** [Nice3point/RevitTemplates#36]
Hello,

While executing the Nuke build automation tool, the process encounters a "ForbiddenException" with the error message indicating that a resource is not accessible by the integration. This issue occurs during the execution of a specific target, resulting in the failure of the build process.
This happened after moving a project from an individual account to an organization on GitHub.

Any idea what can be the reason?

Thanks,
Yuval

![2023-06-12_8-06-16](https://github.com/Nice3point/RevitTemplates/assets/131056194/7cc8ae8f-5b4c-485a-8a8c-61ecd4d24303)

**Comment by Nice3point** [comment]
I guess you don't have repository permissions to create a release on GitHub

**Comment by Yuvdal** [comment]
Indeed that was the problem.
I had to change the workflow permissions to "read and write permissions".
Thank you!

**Comment by gaborschnierer** [comment]
A bit more info. For personal GitHub accounts, you don't have an organisation.
What I did (probably the same as @Yuvdal) is add permissions to the workflow file.

name: Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!main'

**permissions: write-all**

jobs:
  windows:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Nuke Build
        run: ./.nuke/build.cmd --GitHubToken ${{ secrets.GITHUB_TOKEN }}
