### ISSUE TITLE
How to add Dependency Injection support

### ISSUE THREAD

**Issue by cesarecaoduro** [Nice3point/RevitTemplates#39]
It will be extremely useful to add a mechanism for integrating dependency injection in the current template, similar to what has been done by [OnBox ](https://github.com/engthiago/Onboxframework).
Services like telemetry or logs should be instantiated in the application and made available to all the commands.

**Comment by cesarecaoduro** [comment]
In a complex application, there are services that you may want to have instantiated as singleton.
Services like logs and telemetry are required across the entire application, and you want to make sure you decouple those from their implementation inside the different commands.
Example: I would like to instantiate a telemetry client in the application entry point as singleton (using some sort of builder), and then have that available in the constructor of the command.

```csharp
[Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    [Journaling(JournalingMode.NoCommandData)]
    public class SimpleCommand: IExternalCommand
    {
        private readonly ITelemetryService _telmetryService;

        public SimpleCommand(ITelmetryService telemetryService, ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            //Code here
            _telemetryService = telemetryService;
        }
}
```

Very common pattern in web development with netcore, but so far I haven't seen a lot of these implementation in the Revit world. The only one is the OnBox framework that I pointed out, but I see I am not sure that has been taken care of in the last couple of year.
You have done an amazing work in pulling together this toolset for Revit developers, and this would just be ice on the cake 😄

**Comment by Nice3point** [comment]
Here's how you can do it:

1. Create a host. I'm using `Microsoft.Extensions.Hosting`
```C#
public static class Host
{
    private static IHost _host;

    public static void Start()
    {
        _host = Microsoft.Extensions.Hosting.Host
            .CreateDefaultBuilder()
            .ConfigureAppConfiguration(SetConfiguration)
            .ConfigureServices(AddServices)
            .Build();

        _host.Start();
    }

    private static void AddServices(HostBuilderContext context, IServiceCollection services)
    {
        services.AddSerilog(LoggerService.Configure);

        services.AddTransient<RevitAddin.Commands.HostedCommand>();
        services.AddTransient<RevitAddinView>();
        services.AddTransient<IRevitAddinViewModel, RevitAddinViewModel>();
    }

    private static void SetConfiguration(IConfigurationBuilder builder)
    {
    }

    public static T GetService<T>() where T : class
    {
        return _host.Services.GetService(typeof(T)) as T;
    }

    public static T GetService<T>(this IServiceProvider serviceProvider) where T : class
    {
        return serviceProvider.GetService(typeof(T)) as T;
    }

    public static void Start(IHost host)
    {
        _host = host;
        host.Start();
    }

    public static void Stop()
    {
        _host.StopAsync();
    }
}
```

2. Create an intefrace. It is required so that the host can create an instance of the new class with resolved dependencies
```C#
public interface IHostedCommand
{
    void Execute(ExternalCommand shell);
}
```

3. Create a command and implement the IHostedCommand interface. In the class constructor specify all the dependencies you need. You can use the primary constructor available in C#12
```C#
public class HostedCommand (RevitAddinView view, ILogger logger, MyDependency dependency) : IHostedCommand
{
    public void Execute(ExternalCommand shell)
    {
        logger.Debug("Hello from DI");
        view.ShowDialog();
    }
}
```

4. In the ExternalCommand that attaches to the Revit ribbon, get a new instance of the previously created HostedCommand and call the Execute method

```C#
[UsedImplicitly]
[Transaction(TransactionMode.Manual)]
public class ModellingCommand : ExternalCommand
{
    public override void Execute()
    {
        Host.GetService<RevitAddin.Commands.HostedCommand>().Execute(this);
    }
}
```

**Comment by ricaun** [comment]
@cesarecaoduro I create this package [ricaun.DI](https://www.nuget.org/packages/ricaun.DI) with the core DI implementation based on the Onbox code.

And here are some extensions for Revit Api: [ricaun.Revit.DI](https://www.nuget.org/packages/ricaun.Revit.DI)

Here is a full example: https://github.com/ricaun-io/RevitAddin.DI.Example

**Comment by Nice3point** [comment]
@ricaun why did you decide to make your own container instead of Microsoft's implementation ? What's the benefit ?)

**Comment by ricaun** [comment]
I already used the Onbox framework when Thiago released, and I needed a simple DI package to add in any project without adding any random dependency.
Microsoft.Extensions.Hosting have too many dependencies, if you only need DI does not worth.
https://www.nuget.org/packages/Microsoft.Extensions.Hosting#dependencies-body-tab

**Comment by Nice3point** [comment]
If you need only DI, you can use this package without any problems https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection

**Comment by Nice3point** [comment]
@cesarecaoduro preview release with DI implementation and samples: https://github.com/Nice3point/RevitTemplates/releases/tag/4.0.0-preview.1.0

**Comment by cesarecaoduro** [comment]
This is amazing...
I am on it to do some testing.

**Comment by Nice3point** [comment]
@cesarecaoduro great, if you have any suggestions let me know, we still have half a month before public release

**Comment by cesarecaoduro** [comment]
Maybe a stupid question: how do I install the templates if they are in
preview?
Are you also looking at the possibility of having a similar solution for
Civil3D and other Autocad based products?

**Comment by Nice3point** [comment]
@cesarecaoduro Nuget generates a command to install)
![изображение](https://github.com/Nice3point/RevitTemplates/assets/20504884/f873b634-0e95-4d52-a90d-625f63a77190)
`dotnet new install Nice3point.Revit.Templates::4.0.0-preview.1.0`

**Comment by Nice3point** [comment]
@cesarecaoduro released 
Description: https://github.com/Nice3point/RevitTemplates/wiki/Templates
Samples: https://github.com/Nice3point/RevitTemplates/tree/main/samples

**Comment by cesarecaoduro** [comment]
Great job!
Thanks for your commitment to the open source community.

Cesare Caoduro
________________________________
