### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by AmeerMansour** [Nice3point/RevitTemplates#41]
hi can you explain how to  publish an application to the Autodesk Store using that template ?

**Comment by Nice3point** [comment]
@AmeerMansour hi, are you having trouble creating a `.bundle` ?

**Comment by Nice3point** [comment]
**Preparing Apps for the Store: Guidelines** https://damassets.autodesk.net/content/dam/autodesk/www/developer-network/app-store/revit/pdf/3%20Autodesk%20Exchange%20Publish%20Revit%20Apps%20-%20Preparing%20Apps%20for%20the%20Store_Guidelines.pdf

**Comment by AmeerMansour** [comment]
yes sorry to bother you but 
how to use this template to generate that structure?

**Comment by Nice3point** [comment]
https://github.com/Nice3point/RevitTemplates/wiki/Autodesk-Store-bundle
just create a solution with the "Bundle support" option enabled
