### ISSUE TITLE
copying from bin

### ISSUE THREAD

**Issue by AmeerMansourWSP** [Nice3point/RevitTemplates#42]
hi 
it seems this doesn't copy folders from build.
![devenv_hMwq1sbAqI](https://github.com/Nice3point/RevitTemplates/assets/146998900/c00d1130-e4fe-45cc-9155-1722cb966280)

1- I add this folder and this image 

![devenv_u1cYofbKcS](https://github.com/Nice3point/RevitTemplates/assets/146998900/e221dab2-4e95-4366-ac8c-0a49724b16c2)

2-it appears in bin folder as it supposed to be 

![explorer_SbN0tWkmzn](https://github.com/Nice3point/RevitTemplates/assets/146998900/88d2d86e-c219-40f7-98f0-e6261def52d1)

3- but it doesn't get copied

![explorer_AdO8X5VhcS](https://github.com/Nice3point/RevitTemplates/assets/146998900/c64a828b-cf4d-487a-a211-0732728e5f53)

how to fix this ?
this is my test project
[RevitAddIn2.zip](https://github.com/Nice3point/RevitTemplates/files/13433538/RevitAddIn2.zip)

**Comment by Nice3point** [comment]
@AmeerMansourWSP hi, try to replace this
![изображение](https://github.com/Nice3point/RevitTemplates/assets/20504884/30e4badf-de6e-489f-9ae8-ff4c4698570a)
with this `$(TargetDir)**\*`

**Comment by AmeerMansourWSP** [comment]
I did that but it will copy the files in the folder into that path but not the folder itself

**Comment by Nice3point** [comment]
@AmeerMansourWSP try it
![изображение](https://github.com/Nice3point/RevitTemplates/assets/20504884/00e524c3-3983-4f64-b354-b83deb76d032)

**Comment by Nice3point** [comment]
@AmeerMansourWSP https://github.com/Nice3point/RevitTemplates/wiki/Third-party-files

**Comment by AmeerMansourWSP** [comment]
thanks it works
