### ISSUE TITLE
New picture does not work in Nuget

### ISSUE THREAD

**Issue by ricaun** [Nice3point/RevitTemplates#44]
Your new banner does not work in the Nuget. (I don't know if you noticed)

![image](https://github.com/Nice3point/RevitTemplates/assets/12437519/571f1a65-7ecc-4963-8366-8eefd8813281)

**Comment by Nice3point** [comment]
I yes, I know, this is a long-known Nuget pain, it still does not allow you to display html tags. but they are needed in the readme to at least set the width of the image https://github.com/NuGet/NuGetGallery/issues/8644

**Comment by ricaun** [comment]
I see, I have a similar issue as well but they were related to the image URL, the Nuget only allows some specific hosts, but I was using the normal markdown image, and I would love to resize it.

Two files look terrible, maybe if you create on the fly eh use regex to replace that with the normal markdown. (It's just a visual so it's not a breaking issue.)

I used a basic approach, a small size image with a dark background. 😅

**Comment by Nice3point** [comment]
I will probably automate this process with Nuke and cut out the image. in general the html code still includes different images for the dark and light GitHub theme, which complicates the process) Yes, I saw your Issue on Nuget, they have a very strict security framework, although both GitHub and Nuget are owned by Microsoft the policy for the Readme is different 🥺

**Comment by Nice3point** [comment]
@ricaun  Fixed) Nuke now just cut out the picture when packing it up
![изображение](https://github.com/Nice3point/RevitTemplates/assets/20504884/d9b3d297-67c6-4654-ab28-7fa6af0744f8)
