### ISSUE TITLE
Conflict to Revitlookup

### ISSUE THREAD

**Issue by yaomogumq** [Nice3point/RevitTemplates#48]
Hi, I am new to the revit development, shout-out to your template. When I am building the MultiProjectSolution sample. It works perfectly. However, the revit lookup pops up the following errors:
![螢幕擷取畫面 2024-04-19 171155](https://github.com/Nice3point/RevitTemplates/assets/79303172/f219625c-c8c4-4e30-a4d2-4c07ced8873f)
May I know how to resolve it, thank you!

Revit version tested out:
2020,2021,2022,2023,2024

**Comment by Nice3point** [comment]
do you have the latest Lookup version installed? Please install the latest and it will be okay https://github.com/jeremytammik/RevitLookup/releases

**Comment by yaomogumq** [comment]
> do you have the latest Lookup version installed? Please install the latest and it will be okay https://github.com/jeremytammik/RevitLookup/releases

yes, it is solved. Thank you!
