### ISSUE TITLE
Constants Missing in Latest?

### ISSUE THREAD

**Issue by johnpierson** [Nice3point/RevitTemplates#53]
Maybe I am missing it, but the precompile constants seem to not come through when starting a Revit Application Plugin from the new templates:
![image](https://github.com/user-attachments/assets/828504b1-de91-4d92-89bf-39a766f79f47)

Left = Before and Right = After

**Comment by Nice3point** [comment]
They now come with the https://github.com/Nice3point/Revit.Build.Tasks package starting with template release 4.0.2. preprocessor symbols are generated automatically, this cleans up the csproj files a lot. WIKI has a more detailed description https://github.com/Nice3point/RevitTemplates/wiki/Multiple-Revit-Versions and also read the Readme for Revit.Build.Tasks.

**Comment by johnpierson** [comment]
Oh cool! Thanks!
