### ISSUE TITLE
Troubleshooting Section

### ISSUE THREAD

**Issue by benkoshy** [Nice3point/RevitTemplates#56]
A proposal to add the following to the Wiki etc: (The background context to this is as follows: 

- https://github.com/Nice3point/RevitTemplates/discussions/54#discussioncomment-10405092 - proposal to open up the wiki for editing by the community.
- https://github.com/Nice3point/RevitExtensions/discussions/6#discussioncomment-10356189  - which is tangential but not irrelevant).

Here is the proposal:

## (A) Target vs CoreLR runtime issue

![image](https://github.com/user-attachments/assets/ede98fb8-c757-4621-abcc-608d00ccb880)

> A fatal error has occurred and debugging needs to be terminated. The debugger was configured to use the Desktop CLR (.NET Framework) Managed debugger, but the target process loaded the CoreCLR (.NET Core) runtime. To debug this project, configure it to use the 'Managed (CoreCLR)' debugger.

The error message is a little confusing and potentially misleading:

One potential solution is to check the "Configuration Manager" for the "Configuration Settings"

![image](https://github.com/user-attachments/assets/8f6eae35-c45c-4e21-ae01-5efcf124b3a3)

### Set it to the correct Configuration For you - Whatever that might be

In my case, I want to set it to R25. Your case may be different.

![image](https://github.com/user-attachments/assets/35d95c9c-9c9b-4691-9eae-b48297fbe8eb)

**Comment by Nice3point** [comment]
As far as I can see, the error is local and is related only to Visual Studio. My fellow programmers do not have it, and neither do I. That's why the problem has nothing to do with templates, and it will be superfluous to mention it when it is simply solved by Google. 

Nevertheless, I have written instructions on how to create a project step by step, I think it will solve many questions. If you think there is something missing, please contact me

https://github.com/Nice3point/RevitTemplates/wiki/Step%E2%80%90by%E2%80%90step-Guide

**Comment by benkoshy** [comment]
> As far as I can see, the error is local and is related only to Visual Studio. My fellow programmers do not have it, and neither do I. That's why the problem has nothing to do with templates, and it will be superfluous to mention it when it is simply solved by Google.
> 
> Nevertheless, I have written instructions on how to create a project step by step, I think it will solve many questions. If you think there is something missing, please contact me

so i've had a look at the change(s) and I think it is good.

> https://github.com/Nice3point/RevitTemplates/wiki/Step%E2%80%90by%E2%80%90step-Guide

I cannot be more effusive in my praise of the maintainer's efforts with this library (and others). PRs have been made as suggestions - to be cast out or retained according to the maintainers' discretion.

It may be likely that your fellow programmers have experience with the Revit API (via Visual Studio) - I on the other hand have zero experience with Revit + the Revit API + any of the tooling. The benefit of knowing nothing: is that everything is questioned, and even the most trivial hurdles (trivial to an expert) stumped me, even if it is tangential / superfluous / and or trivially solved via Google. Also in my experience with FOSS - it is the newbies who capture the vast majority of maintainers' time - anything which might save a maintainer's time without burdening the experts might be worthy of clarification. Of course, everything has a maintenance overhead, so the maintainer may best decide whether to include or remove material.

lasty re: the R25 config issue - I later saw that some other newbie also had the same problem. x2 people with the same problem? and asking the same question? That's a waste of the maintainer's time: so I resolved to document it via trouble shooting. 

PRs are not created trivially. I will only do it is a "last resort" if it think it worthwhile to the community, and to let the maintainer decide what to do with it.

**Comment by Nice3point** [comment]
Thanks for the clarification, I try to take into account all the problems that developers have and document them over time, so I'm glad when questions arise, because it's easier to maintain this project, handy for everyone. However, issues directly related to Visual Studio will most likely be rejected
