### ISSUE TITLE
Issue in turning the configuration to Revit 25 in the constructor of the view

### ISSUE THREAD

**Issue by CG-KhalidFathy** [Nice3point/RevitTemplates#57]
When I use any configuration to test the button in Revit, it works fine for all versions except Revit 2025.
![image](https://github.com/user-attachments/assets/7e43b567-eba6-4f1a-b996-f831f3e08cae)
Here's how I solved it: I created my own initializer for the window. I developed an extension method for the window where I pass the URI, which represents the location of my window within the solution.
```
public static void LoadViewFromUri(this Window window, string baseUri)
{
  
    var resourceLocater = new Uri(baseUri, UriKind.Relative);
    var exprCa = (PackagePart)typeof(Application).GetMethod("GetResourceOrContentPart", BindingFlags.NonPublic | BindingFlags.Static).Invoke(null, new object[] { resourceLocater });
    var stream = exprCa.GetStream();
    var uri = new Uri((Uri)typeof(BaseUriHelper).GetProperty("PackAppBaseUri", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null, null), resourceLocater);
    var parserContext = new ParserContext
    {
      BaseUri = uri
    };
    typeof(XamlReader).GetMethod("LoadBaml", BindingFlags.NonPublic | BindingFlags.Static).Invoke(null, new object[] { stream, parserContext, window, true });
 
}
```

![image](https://github.com/user-attachments/assets/f2138661-e130-450f-af03-22d8295f7b43)

with this implementation it works fine
![image](https://github.com/user-attachments/assets/48552478-b249-47c9-9c89-7b586d03e563)

**Comment by Nice3point** [comment]
Hi, the topic is not related to templates, but to RevitToolkit where there are suggestions on how to workaround this problem, and some other tips https://github.com/Nice3point/RevitToolkit/issues/7
